import { Camera, CameraHelper, MeshBasicMaterial, MeshNormalMaterial, OrthographicCamera, PerspectiveCamera, Vector3 } from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls';
import UVMaterial from './UVMaterial';
export type MultiViewMode = 'Single' | 'Side by Side' | 'Stacked' | 'Quad';
export declare const ModeOptions: MultiViewMode[];
export declare const cameras: Map<string, Camera>;
export declare const controls: Map<string, OrbitControls>;
export declare const helpers: Map<string, CameraHelper>;
export declare const cameraOptions: string[];
export declare function createOrtho(name: string, position: Vector3): OrthographicCamera;
export declare const debugCamera: PerspectiveCamera;
export type RenderMode = 'Default' | 'Normals' | 'Wireframe' | 'UVs';
export declare const renderOptions: RenderMode[];
export declare const normalsMaterial: MeshNormalMaterial;
export declare const wireframeMaterial: MeshBasicMaterial;
export declare const uvMaterial: UVMaterial;
